name: remote ssh command

on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/immersive:latest          
    - 
      name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git pull origin main 
          docker stop immersive 
          docker rm immersive
          docker rmi ${{ secrets.DOCKER_USER }}/immersive
          docker pull ${{ secrets.DOCKER_USER }}/immersive-
          docker run -d -p 80:80 -e SERVER_PORT=${{ secrets.SERVER_PORT }} --name immersive ${{ secrets.DOCKER_USER }}/immersive:latest 
